################################################# Injector Parameters #################################################
#
#    hdf5_file                    the path to the hdf5 file to corrupt
#
#    injection_probability        the probability to corrupt each value
#    injection_type               one of the following strings {"percentage", "count"}
#    injection_tries              is either a real number between [0-1] or a int > 0, depending if injection_type
#                                 is "percentage" or "count", respectively.
#
#    log_file_path                path where to save the log files.
#
#    first_bit                    first bit to inject errors (0-63), it must be <= than last_bit.
#    last_bit                     last bit to inject errors (0-63), it must be >= than first_byte.
#                                 If both values are the same, injection will only happen on that bit.
#
#    allow_sign_change            True,   when corruption is on float value, even if the sign-bit (0) is not included
#                                         in the above range, it will also enable bit flips on it.
#                                 False,  it respects the above range.
#
#    allow_NaN_values             when flipping a bit of the in a double, the resulting binary can represent a NaN or
#                                 Inf, if set to False, the corruption mechanism will never produce such values.
#
#    use_random_locations         choose random locations on the file to inject errors,
#                                 if true it will ignore the locations_to_corrupt
#
#    locations_to_corrupt         list of locations to try to inject errors
################################################# Injector Parameters #################################################

hdf5_file: "/home/diego/Documents/hdf5_files/otherFiles/ckpt_tf_vgg_e_5.h5"
injection_probability: 1 # 1e-8
injection_type: "count" #"percentage"
injection_tries: 2000
log_file_path: "/home/diego/PycharmProjects/hdf5_corrupter/"
first_bit: 1
last_bit: 2
allow_sign_change: False
allow_NaN_values: True
use_random_locations: True
locations_to_corrupt:
  - "/batch_normalization/batch_normalization/beta:0"
  - "/batch_normalization/batch_normalization/gamma:0"
  - "/batch_normalization/batch_normalization/moving_mean:0"
  - "/batch_normalization/batch_normalization/moving_variance:0"