################################################# Injector Parameters #################################################
#
#    hdf5_file                    the path to the hdf5 file to corrupt
#
#    injection_probability        the probability to corrupt each value
#    injection_type               one of the following strings {"percentage", "count"}
#    injection_tries              is either a real number between [0-1] or a int > 0, depending if injection_type
#                                 is "percentage" or "count", respectively.
#
#    first_byte                   first byte to inject errors (0-7) -1 random, it must be <= than last_byte.
#    last_byte                    last byte to inject errors (0-7) -1 random, it must be >= than first_byte.
#                                 If both values are the same, injection will only happen on that byte.
#                                 Note that first_byte = 0, it's the same as first_byte = -1
#                                 Note that last_byte = 7,  it's the same as last_byte = -1
#
#    bit                          which bit is faulty (0-7), -1 random
#
#    allow_NaN_values             when flipping a bit of the in a double, the resulting binary can represent a NaN or
#                                 Inf, if set to False, the corruption mechanism will never produce such values.
#
#    use_random_locations         choose random locations on the file to inject errors,
#                                 if true it will ignore the locations_to_corrupt
#
#    locations_to_corrupt         list of locations to try to inject errors
################################################# Injector Parameters #################################################

hdf5_file: "/home/diego/Documents/hdf5_files/model_epoch_2_chainer.h5"
injection_probability: 1 # 1e-8
injection_type: "count" #"percentage"
injection_tries: 5
first_byte: -1
last_byte: -1
bit: -1
allow_NaN_values: True
use_random_locations: False
locations_to_corrupt:
  - "/predictor/conv1/W"
  - "/predictor/conv1/b"
  - "/predictor/res2/0/bn1/N"
  - "/predictor/res2/0/bn4/avg_var"
  - "/predictor/res3/2/conv2/W"