############### Injector Parameters ##################
#
#    hdf5_file - the path to the hdf5 file to corrupt
#    prob - probability to inject corruption
#    corruption_percentage - value between 0-100, it represents the percentage of entries to corrupt (based on the HDF5 amount of entries)
#    byte - which byte is faulty (0-7) -1 random
#    singleInj - one injection at most per hdf5 file (0 or 1)
#    locations_to_corrupt - list of locations to try to inject errors
# do we need a probability of injection? here we definitely want to inject errors
#####################################################

hdf5_file: "/home/diego/Documents/hdf5_files/model_epoch_2_chainer.h5"
#prob: 1e-8
prob: 1
max_corruption_percentage: 1e-3
singleInj: 1
byte: -1
bit: -1
locations_to_corrupt:
  - "/predictor/conv1/W"
  - "/predictor/conv1/b"
  - "/predictor/res2/0/bn1/N"
  - "/predictor/res2/0/bn4/avg_var"
  - "/predictor/res3/2/conv2/W"