############### Injector Parameters ##################
#
#    hdf5_file - the path to the hdf5 file to corrupt
#    print_only - just print the contents of the file without injecting any error
#    print_level - from 1 - 3
#    prob - probability to inject corruption
#    byte - which byte is faulty (0-7) -1 random
#    singleInj - one injection at most per hdf5 file (0 or 1)
#    locations_to_corrupt - list of locations to try to inject errors
# do we need a probability of injection? here we definitely want to inject errors
#####################################################

hdf5_file: "/home/diego/Documents/hdf5_files/checkpoint-tensorFlow.h5"
prob: 1e-7
singleInj: 1
byte: -1
bit: -1
locations_to_corrupt:
  - "/batch_normalization/batch_normalization/beta:0"
  - "/batch_normalization/batch_normalization/gamma:0"
  - "/batch_normalization/batch_normalization/moving_mean:0"
  - "/batch_normalization/batch_normalization/moving_variance:0"