PROB = 1e-7
MAX_CORRUPTION_PERCENTAGE = 1e-5
PRINT_ONLY = False
FIRST_BYTE = -1   # -1 means random
LAST_BYTE = -1   # -1 means random
BIT = -1    # -1 means random
USE_RANDOM_LOCATIONS = True
ALLOW_NaN_VALUES = False
LOCATIONS_TO_CORRUPT = []
HDF5_FILE = ""

STR_HDF5_FILE = "hdf5_file"
STR_PROB = "prob"
STR_MAX_CORRUPTION_PERCENTAGE = "max_corruption_percentage"
STR_FIRST_BYTE = "first_byte"
STR_LAST_BYTE = "last_byte"
STR_BIT = "bit"
STR_USE_RANDOM_LOCATIONS = "use_random_locations"
STR_ALLOW_NaN_VALUES = "allow_NaN_values"
STR_LOCATIONS_TO_CORRUPT = "locations_to_corrupt"
