INJECTION_PROBABILITY = -1
INJECTION_TYPE = ""
INJECTION_TRIES = -1

ONLY_PRINT = False
FIRST_BIT = 0
LAST_BIT = 63
ALLOW_SIGN_CHANGE = True
USE_RANDOM_LOCATIONS = True
ALLOW_NaN_VALUES = False
LOCATIONS_TO_CORRUPT = []
HDF5_FILE = ""
LOG_FILE_PATH = ""

STR_HDF5_FILE = "hdf5_file"
STR_LOG_FILE_PATH = "log_file_path"

STR_INJECTION_PROBABILITY = "injection_probability"
STR_INJECTION_TYPE = "injection_type"
STR_INJECTION_TRIES = "injection_tries"
STR_FIRST_BIT = "first_bit"
STR_LAST_BIT = "last_bit"
STR_ALLOW_SIGN_CHANGE = "allow_sign_change"
STR_USE_RANDOM_LOCATIONS = "use_random_locations"
STR_ALLOW_NaN_VALUES = "allow_NaN_values"
STR_LOCATIONS_TO_CORRUPT = "locations_to_corrupt"

STR_COUNT = "count"
STR_PERCENTAGE = "percentage"
CORRUPTION_TYPE_VALUES = [STR_PERCENTAGE, STR_COUNT]